name: REhints
description: Sharing reverse engineering knowledge
url: http://rehints.com
timezone: America/Portland
future: false
highlighter: pygments
markdown: kramdown
permalink: :year-:month-:day-:title.html
